### ISSUE TITLE
Melhorar fichamento de 1 - 2018 - Dispositivos vestíveis.md

### ISSUE THREAD

**Issue by fboldt** [MatheusMol2021/Fichamentos_Artigos#5]
Como você colocou importância alta (1) nesse artigo, é bem provável que você o cite no seu anteprojeto. Então, você tem que escrever um texto explicando como este artigo se relaciona com seu trabalho. Assim, você só vai copiar e colar esse texto no seu documento.

**Comment by MatheusMol2021** [comment]
OK, vou dar prioridade

**Comment by fboldt** [comment]
É pra você fechar o issue depois de terminar a tarefa, não depois de lê-lo.

**Comment by MatheusMol2021** [comment]
OK, fichamento concluído,

Eu fui escrevendo conforme penso em inserir no anteprojeto, assim eu só teria que copiar e colar citando o autor, conforme sua orientação.
